language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - sed -i -e 's|AC_PREREQ(\[2.69\])|AC_PREREQ([2.68])|' configure.ac
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq; fi

install:
  - mkdir sdl_root
  - export SDL_PREFIX="$PWD/sdl_root"
  - export PATH="$SDL_PREFIX/bin:$PATH"
  - export PKG_CONFIG_PATH="$SDL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  - wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz -O - | tar -xz
  - (cd SDL2-2.0.4 && ./configure --prefix=$SDL_PREFIX && make -j5 && make install)
  - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz -O - | tar -xz
  - (cd SDL2_mixer-2.0.1 && ./configure --prefix=$SDL_PREFIX && make -j5 && make install)
  - git clone https://github.com/google/styleguide.git ./styleguide
  - export CPPLINT_PATH="$PWD/styleguide/cpplint"

script:
  - $CPPLINT_PATH/cpplint.py ./src/*.cc ./src/*.h ./windows/*.cc ./windows/*.h
  - ./bootstrap && ./configure --enable-sdl2-mixer
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then make dist-osx; else make -j5 distcheck; fi
