version: '{build}'
configuration:
  - Debug
  - Release

install:
  # SDL2
  - ps: Start-FileDownload https://libsdl.org/release/SDL2-devel-2.0.3-VC.zip
  - ps: 7z x SDL2-devel-2.0.3-VC.zip -oC:\

  - ps: $env:SDL2_INCLUDE = "C:\SDL2-2.0.3\include"
  - ps: $env:SDL2_LIB = "C:\SDL2-2.0.3\lib\x86"

  # SDL2_mixer
  - ps: Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.0-VC.zip
  - ps: 7z x SDL2_mixer-devel-2.0.0-VC.zip -oC:\

  - ps: $env:SDL2_MIXER_INCLUDE = "C:\SDL2_mixer-2.0.0\include"
  - ps: $env:SDL2_MIXER_LIB = "C:\SDL2_mixer-2.0.0\lib\x86"

build_script:
  - msbuild windows\freeserf.sln
